basic:
    name: brands-666
    environments:
        production: 'https://orkin.findpestpros.com/ants/'
        staging: 'https://orkinpest-findpestpros-com-git-story-brands-666-home-solutions.vercel.app/ants/'
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
